name: ansible-lint.yml
on:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Ansible and Ansible-Lint
      - name: Install Ansible and Ansible-Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      # ✅ Ensure required directories and files exist before running ansible-lint
      - name: Create missing directories and files
        run: |
          mkdir -p scheduler/playbooks utils/playbooks
          touch scheduler/playbooks/kubernetes_sigs.kubespray.cluster
          touch utils/playbooks/kubernetes_sigs.kubespray.remove_node
          touch utils/playbooks/kubernetes_sigs.kubespray.reset

      # ✅ Ensure /var/log/omnia.log is writable
      - name: Ensure /var/log/omnia.log is writable
        run: |
          sudo mkdir -p /var/log
          sudo touch /var/log/omnia.log
          sudo chmod 666 /var/log/omnia.log

      # ✅ Run ansible-lint
      - name: Run ansible-lint
        run: |
          ansible-lint -x 305 \
            omnia.yml \
            discovery_provision.yml \
            local_repo/local_repo.yml \
            server_spec_update/server_spec_update.yml \
            scheduler/job_based_user_access.yml \
            security/user_passwordless_ssh.yml \
            storage/nfs_sas.yml \
            storage/powervault.yml \
            telemetry/add_node_idrac.yml \
            tools/jupyterhub.yml \
            tools/kserve.yml \
            tools/kubeflow.yml \
            tools/pytorch.yml \
            tools/tensorflow.yml \
            tools/vllm.yml \
            utils/control_plane_cleanup.yml \
            utils/delete_node.yml \
            utils/remove_node_configuration.yml \
            utils/reset_cluster_configuration.yml \
            utils/update_user_repo.yml \
            utils/servicetag_host_mapping.yml \
            utils/software_update/software_update.yml \
            utils/timescaledb_utility/timescaledb_utility.yml \
            utils/ip_rule_assignment/ip_rule_assignment.yml \
            utils/nodeinfo_db/nodeinfo_db.yml

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
